In [1]:
import nsepy
from nsepy import get_history

from datetime import date

In [3]:
import pandas as pd

In [2]:
start_date = date(2017,3,1)
end_date = date.today()


tata_motors = nsepy.get_history(symbol="TataMotors", start= start_date, end= end_date)

tata_motors

                Symbol Series  Prev Close    Open  ...      Turnover  Trades  Deliverable Volume  %Deliverble
Date                                               ...
2017-03-01  TATAMOTORS     EQ      456.75  455.90  ...  3.772610e+14  141268             5264418       0.6291
2017-03-02  TATAMOTORS     EQ      449.45  457.85  ...  6.328546e+14  147115             5383593       0.3939
2017-03-03  TATAMOTORS     EQ      461.70  463.30  ...  3.269498e+14  111096             3892320       0.5493
2017-03-06  TATAMOTORS     EQ      459.95  462.50  ...  1.888121e+14   59743             1294887       0.3208
2017-03-07  TATAMOTORS     EQ      470.80  469.50  ...  3.346950e+14  114627             2930474       0.4119
...                ...    ...         ...     ...  ...           ...     ...                 ...          ...
2022-02-23  TATAMOTORS     EQ      478.25  481.75  ...  8.503351e+14  205394             4920749       0.2779
2022-02-24  TATAMOTORS     EQ      477.00  455.95  ...  2.542080e+15  775585            18193568       0.3177
2022-02-25  TATAMOTORS     EQ      427.95  444.85  ...  2.243688e+15  536058             8001318       0.1637
2022-02-28  TATAMOTORS     EQ      459.75  445.00  ...  1.559657e+15  355388             8824925       0.2560
2022-03-02  TATAMOTORS     EQ      454.05  452.95  ...  1.158714e+15  335482             7350453       0.2850

[1240 rows x 14 columns]

In [5]:
tata_motors.to_csv(r'Tata_Motors_stock.csv')

In [14]:
companies = {"M&M", "MARUTI", "ASHOKLEY", "EICHERMOT"}

In [15]:
for company in companies:
    
    company_new = company.replace("&","%26")
    stock_data = nsepy.get_history(symbol=company_new, start=start_date, end=end_date)
    file_name = '{}.csv'.format(company)
    stock_data.to_csv(file_name, encoding= 'utf-8')